# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Dharak Kharod'
tagline:          'another computer science blog'
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Dharak Kharod
  url:            https://twitter.com/dharakk
  email:          dharakkharod@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
